# PostgreSQL Configuration

#spring.datasource.url=jdbc:postgresql://localhost:5432/expense_db
#spring.datasource.username=postgres
#spring.datasource.password=password

spring.datasource.url=jdbc:postgresql://ep-silent-frost-ao2orc6m.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HIsZcTQVk52l
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#spring.flyway.repair=true
#spring.profiles.active=local
spring.profiles.active=prod
#spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.api-key=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
spring.ai.retry.enabled=false

# Email Configuration (Configure with your SMTP settings)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santoshganapa@gmail.com
app.default.user=santoshganapa
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Application Settings
app.notifications.enabled=true
server.port=${PORT:8080}